apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  namespace: fraud-detection
  annotations:
    openshift.io/display-name: fraud-detection
    serving.kserve.io/deploymentMode: ModelMesh
  name: fraud-detection
  labels:
    name: fraud-detection
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    model:
      modelFormat:
        name: onnx
        version: '1'
      runtime: ovms
      storage:
        key: aws-connection-fraud-detection
        path: fraud-detection.onnx
